# Generated by Django 5.2.15 on 2026-06-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=150)),
                ('survey_number', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('plot', 'Plot'), ('flat', 'Flat'), ('house', 'House'), ('shop', 'Shop'), ('land', 'Land')], max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('owner_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('property_image', models.ImageField(upload_to='property_images/')),
                ('registration_pdf', models.FileField(upload_to='property_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
